# Generated by Django 5.2.12 on 2026-05-07 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_remove_profile_role_profile_roles'),
        ('localevents', '0003_event_capacity_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='user_registrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_signups', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(blank=True, related_name='organized_events', to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
