# Generated by Django 6.0.2 on 2026-02-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'project categories'},
        ),
    ]
