# Generated by Django 5.2.12 on 2026-05-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0003_project_creator_favorite_projectrating_projectreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreview',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
